### ISSUE TITLE
a bit of question

### ISSUE THREAD

**Issue by Hausenbourne** [Bastlirovo/sharp-memory-lcd-breakout#1]
Hello, my friend, I'm working on a project, which needs to use SHRP memory LCD. I don't have much hardware experience. I see that the driver circuit in the official data book is very simple, including several capacitors and a voltage regulator circuit. In addition, I see the sharp memory LCD breakboard sold online It's just a few resistors and capacitors. It doesn't solder the voltage regulator chip, but mc74hc4050n is used in your breakboard. I want to know if it's necessary to add this chip and what role it plays.

**Comment by Bastlirovo** [comment]
Hi Hosenbone. I think, that I understand you confusion. This Sharp display uses 5 Volts for Power and 3.3 Volts for communication. I'm using the ESP32 for data wires, so that is why I don't need to use mc74hc4050n or different Voltage Shifter - my ESP is using 3.3V for data wires. But I need StepUp Voltage Booster to create 5V for display power.

If you're planning to use 5V MCU, you will need to shift the voltage for Data wires from 3.3V to 5V, where mentioned mc74hc4050n shall work fine.

**Comment by Hausenbourne** [comment]
Yes, I understand what you mean, but the only thing I am confused about is that you add mc74hc4050n to the PCB file, I don't know the function of adding this module to it. Because the driver circuit in the official data manual does not mention this module.

Your PCB file:
![image](https://user-images.githubusercontent.com/36794123/106406570-a4468100-6474-11eb-9703-22e3aa00d33e.png)
Official data manual:
![image](https://user-images.githubusercontent.com/36794123/106407040-f5a34000-6475-11eb-8fbe-b3b25a1a0e25.png)

**Comment by Bastlirovo** [comment]
There is some misunderstanding, I'm not using this chip and your picture of board is from different repository.
Please see the Eagle files again, or this PDF version of schematic https://github.com/Bastlirovo/sharp-memory-lcd-breakout/blob/main/HW/sharp_breakout_v1.pdf
